language: python

# sudo false implies containerized builds
sudo: false

os:
  - linux

python:
  - "2.7"
  - "3.5"
  - "3.6-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

# command to install dependencies
# install: "pip install -r requirements.txt"
# command to run tests
# script: nosetests

env:
  # list package dependencies
  - PYEIT_DEPS="pytest cpplint numpy scipy pandas matplotlib"
  # package name for test invocation
  - TESTNAME="tests"
  # code analysis
  - TASK=lint
  # build analysis
  - TASK=build

addons:
  apt:
    packages:
      - doxygen
      - wget
      - git
      - libcurl4-openssl-dev
      - unzip
      - libatlas-dev
      - gcc-5.0
      - g++-5.0

before_install:
  - source scripts/travis/travis_setup_env.sh

install:
  - source scripts/travis/setup.sh

script:
  - pytest $TESTNAME

cache:
  directories:
    - ${HOME}/.cache/usr

before_cache:
  - scripts/travis/travis_before_cache.sh

after_failure:
  - scripts/travis/travis_after_failure.sh

notifications:
  email:
    on_success: change
    on_failure: always

